### ISSUE TITLE
Documentation fix

### ISSUE THREAD

**Issue by jordanboston** [Deveodk/vue-toastr#1]
This is working great, but the documentation threw me off a little.  I think these need a closing quote for the string: `this.$toastr('success', 'i am a toastr success', 'hello');`

Right now they are like this `'success,`

Once I changed that it worked wonderfully.  Just may want to update the docs so it will work for people copy/pasting it in.  Thanks!

**Comment by NicolaiRamsby** [comment]
Hi @jordanboston ! Thanks a lot for your interest in our package! We've just updated our readme so future users won't experience the same as you. Thanks a lot for your feedback!
